services:
  postgres:
    image: postgres:16
    container_name: quanlykhachhang_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: qlkh_db
      POSTGRES_USER: qlkh_user
      POSTGRES_PASSWORD: qlkh_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

