CREATE TABLE IF NOT EXISTS app_info (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_info (name)
VALUES ('QUANLYKHACHHANG')
ON CONFLICT DO NOTHING;

