const implemented = {
  MCN: {
    profileField: 'primary_branch_code',
    actualSource: 'DP01 + LN01 + PF14 + CN05',
    calculation: 'Chọn chi nhánh chính có primary_location_score cao nhất từ tổng quy mô tiền gửi, dư nợ và số dịch vụ của khách hàng.',
    reconciliation: 'Đối chiếu mã chi nhánh đã chọn với branch_details; kiểm tra chi nhánh có điểm cao nhất và tồn tại trong file nguồn.',
  },
  MPGD: {
    profileField: 'primary_pgd_code',
    actualSource: 'DP01',
    calculation: 'Lấy mã PGD của chi nhánh chính từ bản ghi DP01; tổng hợp theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu MPGD với MA_PGD của DP01 và danh mục phòng giao dịch.',
  },
  MKH: {
    profileField: 'ma_kh',
    actualSource: 'DP01',
    calculation: 'Chuẩn hóa TRIM(MA_KH_CHUAN); nếu trống dùng TRIM(MA_KH). DP01 là tập khách hàng nền.',
    reconciliation: 'Khóa duy nhất theo kỳ là period_key + MA_KH; dùng cùng khóa để nối LN01, PF14 và CN05.',
  },
  TENKH: {
    profileField: 'ten_kh',
    actualSource: 'DP01',
    calculation: 'Lấy MAX(TEN_KH) trong các tài khoản DP01 của cùng MA_KH tại chi nhánh.',
    reconciliation: 'So sánh tên với DP01 theo MA_KH; cảnh báo khi một MA_KH có nhiều tên khác nhau.',
  },
  LOAIKH: {
    profileField: 'loai_khach_hang',
    actualSource: 'DP01',
    calculation: 'Ưu tiên CUST_TYPE_NAME, nếu trống dùng CUST_TYPE; lấy MAX khi khách hàng có nhiều tài khoản.',
    reconciliation: 'Đối chiếu giá trị với danh mục loại khách hàng IPCAS và DP01.',
  },
  DIEN_THOAI: {
    profileField: 'telephone',
    actualSource: 'DP01',
    calculation: 'Lấy MAX(TELEPHONE) khác NULL của các bản ghi DP01 cùng MA_KH.',
    reconciliation: 'Chuẩn hóa số điện thoại, kiểm tra độ dài và các số khác nhau trên cùng MA_KH.',
  },
  MACB: {
    profileField: 'ma_cb',
    actualSource: 'LN01 + người dùng hệ thống',
    calculation: 'Chọn cán bộ của khoản vay có dư nợ lớn nhất; mã IPCAS được chuẩn hóa và nối với danh mục người dùng.',
    reconciliation: 'Đối chiếu OFFICER_IPCAS trong LN01 với IPCAS_USERNAME của người dùng đang hoạt động.',
  },
  TENCB: {
    profileField: 'ten_can_bo',
    actualSource: 'LN01 + người dùng hệ thống',
    calculation: 'Tên cán bộ lấy từ tài khoản hệ thống khớp OFFICER_IPCAS của khoản vay dư nợ lớn nhất.',
    reconciliation: 'Đối chiếu mã cán bộ, username IPCAS và họ tên trong danh mục người dùng.',
  },
  DS_TKTT: {
    profileField: 'doanh_so_chuyen_tien_ve_tk',
    actualSource: 'DP01 kỳ hiện tại + kỳ trước',
    calculation: 'MAX(0, tổng số dư DP01 quy đổi kỳ hiện tại - tổng số dư quy đổi kỳ trước) theo MA_KH.',
    reconciliation: 'Đối chiếu tổng số dư hai kỳ, tỷ giá từng CCY và bảo đảm kết quả không âm.',
  },
  SODU_TGCKH: {
    profileField: 'so_du_tien_gui',
    actualSource: 'PF14 + tỷ giá DP01',
    calculation: 'SUM(MONTHLYENDBALANCE × EXCHANGE_RATE) với MONTERM > 0, theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu tổng PF14 theo MA_KH/chi nhánh/CCY và bảng tỷ giá của kỳ.',
  },
  SODU_TKTTBQ: {
    profileField: 'so_du_tgtt_binh_quan',
    actualSource: 'PF14 + tỷ giá DP01',
    calculation: 'SUM(AVERAGEBALANCE × EXCHANGE_RATE) với MONTERM = 0, theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu tổng số dư bình quân PF14 theo MA_KH/chi nhánh và từng loại tiền.',
  },
  DUNO_NHTT: {
    profileField: 'du_no_ngan_han',
    actualSource: 'PF10',
    calculation: 'SUM(EOMBAL) theo mã KH lõi và các chi nhánh với LNTYPE = 100.',
    reconciliation: 'Chỉ đưa vào Profile khi mã KH lõi có trong DP01 của kỳ; chi tiết giữ theo TRBRCD và ACCTNO.',
  },
  DUNO_NHTTBQ: {
    profileField: 'du_no_ngan_han_bq',
    actualSource: 'PF10',
    calculation: 'SUM(AVGBAL) theo mã KH lõi và các chi nhánh với LNTYPE = 100.',
    reconciliation: 'Đối chiếu tổng các LDS PF10 theo khách hàng, chi nhánh và loại vay 100.',
  },
  DUNO_TDHTT: {
    profileField: 'du_no_trung_dai_han',
    actualSource: 'PF10',
    calculation: 'SUM(EOMBAL) với LNTYPE thuộc 110 hoặc 120.',
    reconciliation: 'Gộp trung hạn và dài hạn ở chỉ tiêu tổng, vẫn giữ mã 110/120 tại chi tiết LDS.',
  },
  DUNO_TDHTTBQ: {
    profileField: 'du_no_trung_dai_han_bq',
    actualSource: 'PF10',
    calculation: 'SUM(AVGBAL) với LNTYPE thuộc 110 hoặc 120.',
    reconciliation: 'Đối chiếu tổng bình quân theo từng chi nhánh trước khi cộng toàn khách hàng.',
  },
  DUNO_TC: {
    profileField: 'du_no_thau_chi',
    actualSource: 'PF10',
    calculation: 'SUM(EOMBAL) với LNTYPE = 241.',
    reconciliation: 'Đối chiếu các LDS thấu chi PF10 theo mã KH lõi và chi nhánh.',
  },
  DUNO_TCBQ: {
    profileField: 'du_no_thau_chi_bq',
    actualSource: 'PF10',
    calculation: 'SUM(AVGBAL) với LNTYPE = 241.',
    reconciliation: 'Đối chiếu bình quân các LDS thấu chi PF10 theo mã KH lõi và chi nhánh.',
  },
  TKSODEP: {
    profileField: 'tk_so_dep',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN TKTT_TK_SODEP > 0 THEN 1 ELSE 0 END) theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu cờ sử dụng với CN05; một bản ghi dương thì khách hàng được xác định có sử dụng.',
  },
  AGRIBANKPLUS: {
    profileField: 'agribank_plus',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN DK_AGRIBANK_PLUS > 0 THEN 1 ELSE 0 END) theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu số lượng đăng ký trên CN05; tổng hợp toàn khách hàng bằng MAX qua các chi nhánh.',
  },
  OTT: {
    profileField: 'tin_nhan_ott',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN DK_AGRIBANK_PLUS_OTT > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu cờ OTT theo MA_KH/chi nhánh trong CN05.',
  },
  EBANKING: {
    profileField: 'e_banking',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN SMS_BANKING > 0 THEN 1 ELSE 0 END); tên trường đích hiện là e_banking.',
    reconciliation: 'Đối chiếu với SMS_BANKING của CN05; cần nghiệp vụ xác nhận phạm vi có đúng toàn bộ E-Banking hay không.',
  },
  SMS_TKTV: {
    profileField: 'sms_nhac_no_vay',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN VV_SMS_TIEN_VAY > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu cờ dịch vụ vay trên CN05 theo MA_KH/chi nhánh.',
  },
  SMS_TKTG: {
    profileField: 'sms_tien_gui',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN TG_SMS_TIEN_GUI > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu cờ dịch vụ tiền gửi trên CN05 theo MA_KH/chi nhánh.',
  },
  THE_GNND: {
    profileField: 'the_ghi_no_noi_dia',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN THE_GHI_NO_NOI_DIA > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu số lượng thẻ ghi nợ nội địa trong CN05.',
  },
  THE_LOCVIET: {
    profileField: 'the_td_loc_viet',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN THE_TIN_DUNG_NOI_DIA > 0 THEN 1 ELSE 0 END); hiện ánh xạ vào cờ thẻ Lộc Việt.',
    reconciliation: 'Đối chiếu THE_TIN_DUNG_NOI_DIA; cần xác nhận nghiệp vụ có đồng nhất với toàn bộ thẻ Lộc Việt.',
  },
  THE_TDQT: {
    profileField: 'the_td_quoc_te',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN THE_TIN_DUNG_QUOC_TE > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu số lượng thẻ tín dụng quốc tế trong CN05.',
  },
  SODU_TKTT: {
    profileField: 'pf14_account_balances.monthlyendbalance',
    actualSource: 'PF14',
    calculation: 'SUM(MONTHLYENDBALANCE × tỷ giá) theo mã KH lõi với MONTERM = 0; chi tiết được khai thác tại tab Tiền gửi.',
    reconciliation: 'Đối chiếu từng ACCOUNTNO, TRBRCD, CUSTSEQ và CCY của PF14; tổng chi tiết phải bằng số dư TKTT của khách hàng.',
  },
  SODU_TGCKHBQ: {
    profileField: 'pf14_account_balances.averagebalance',
    actualSource: 'PF14',
    calculation: 'SUM(AVERAGEBALANCE × tỷ giá) theo mã KH lõi với MONTERM > 0.',
    reconciliation: 'Đối chiếu số dư bình quân từng tài khoản PF14 có kỳ hạn trước khi cộng theo khách hàng và chi nhánh.',
  },
  PHAN_LOAIKH: {
    profileField: 'bc06_customer_classifications.segment_branch',
    actualSource: 'BC06',
    calculation: 'Lấy SEGMENT_BRANCH theo mã khách hàng và chi nhánh tại kỳ; lịch sử phân khúc được giữ theo từng kỳ BC06.',
    reconciliation: 'Đối chiếu CUSTOMER_CODE, BRANCH_CODE và CLASSIFICATION_MONTH của BC06; không ghi đè phân khúc giữa các chi nhánh.',
  },
  DUNO_XAU: {
    profileField: 'bc29_customer_credit_risks.total_outstanding',
    actualSource: 'BC29',
    calculation: 'SUM(TOTAL_OUTSTANDING) theo khách hàng với DEBT_GROUP thuộc 3, 4 hoặc 5.',
    reconciliation: 'Đối chiếu tổng dư nợ BC29 theo CUSTOMER_CODE/BRANCH_CODE và nhóm nợ; kỳ không có nhóm 3-5 được ghi nhận là không phát sinh.',
  },
  DUNO_XLRR: {
    profileField: 'bc29_customer_credit_risks.handled_risk_amount',
    actualSource: 'BC29',
    calculation: 'SUM(HANDLED_RISK_AMOUNT) theo mã khách hàng và chi nhánh trong kỳ.',
    reconciliation: 'Đối chiếu CUSTOMER_CODE, ngày xử lý rủi ro và số tiền xử lý tại BC29 trước khi cộng toàn khách hàng.',
  },
  DPRR_CHUNG_TT: {
    profileField: 'dprr_chung_tt',
    actualSource: 'LN01',
    calculation: '(SUM(DU_NO nhóm 1-4 kỳ này) - SUM(DU_NO nhóm 1-4 kỳ trước)) × 0,75%, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu CUSTSEQ, BRCODE và NHOM_NO giữa hai kỳ LN01; giá trị âm được giữ để phản ánh hoàn nhập.',
  },
  DPRR_CHUNG_LK: {
    profileField: 'dprr_chung_lk',
    actualSource: 'LN01',
    calculation: 'SUM(DU_NO nhóm 1-4 cuối kỳ) × 0,75%, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu CUSTSEQ, BRCODE, NHOM_NO và tổng DU_NO của LN01 tại kỳ.',
  },
  DPRR_CUTHE_TT: {
    profileField: 'dprr_cuthe_tt',
    actualSource: 'BC29',
    calculation: 'SUM(SO_TRICH_LAP_TRONG_KY nhóm 2-5 kỳ này) trừ cùng chỉ tiêu kỳ trước, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu MA_KH, BRANCH_CODE và NHOM_NO giữa hai kỳ BC29; giá trị âm là hoàn nhập.',
  },
  DPRR_CUTHE_LK: {
    profileField: 'dprr_cuthe_lk',
    actualSource: 'BC29',
    calculation: 'SUM(SO_TRICH_LAP_TRONG_KY) của nhóm nợ 2-5 tại kỳ, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu MA_KH, BRANCH_CODE, NHOM_NO và SO_TRICH_LAP_TRONG_KY trong BC29.',
  },
  PHI_BAOLANH: {
    profileField: 'phi_bao_lanh',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 7040: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản 7040xx và tổng phát sinh Có/Nợ trong KH02.',
  },
  PHI_CHUYENTIEN: {
    profileField: 'phi_chuyen_tien',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 711001 hoặc 711002: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản phí chuyển tiền và tổng phát sinh Có/Nợ trong KH02.',
  },
  PHI_NHDT: {
    profileField: 'phi_nhdt',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 711036, 711037 hoặc 711039: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản phí NHĐT và tổng phát sinh Có/Nợ trong KH02.',
  },
  ABIC_BATD: {
    profileField: 'abic_batd',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 714: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản 714xxx và tổng phát sinh Có/Nợ trong KH02.',
  },
  LOATHANTAI: {
    profileField: 'loa_bien_dong_so_du',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN LOA_BIEN_DONG_SO_DU > 0 THEN 1 ELSE 0 END) theo mã khách hàng và chi nhánh.',
    reconciliation: 'Đối chiếu cờ sử dụng loa biến động số dư trong CN05; không suy diễn từ Agribank Plus hoặc SMS.',
  },
};

export function mappingRuleFor(field) {
  return implemented[field.code] || {
    profileField: null,
    actualSource: field.source,
    calculation: `Chưa có cột đích hoặc công thức xử lý trong customer_period_profiles. Nguồn dự kiến: ${field.source}.`,
    reconciliation: 'Chưa triển khai đối chiếu tự động; cần chốt nguồn, khóa nối và quy tắc nghiệp vụ trước khi đưa vào Profile.',
  };
}
