const implemented = {
  MCN: {
    profileField: 'primary_branch_code',
    actualSource: 'User–CIF → DP01 tổng số dư → BC06 → LN01 → CIF',
    calculation: 'Ưu tiên user được gắn trực tiếp mã CIF. Nếu không có, cộng số dư DP01 theo từng chi nhánh và chọn chi nhánh có tổng số dư lớn nhất; chỉ khi không có DP01 mới dự phòng BC06, LN01 rồi CIF.',
    reconciliation: 'Đối chiếu chi nhánh chính với chi tiết quan hệ; khi dùng DP01 phải là chi nhánh có tổng số dư lớn nhất của đúng khách hàng trong kỳ.',
  },
  MPGD: {
    profileField: 'primary_pgd_code',
    actualSource: 'Phòng ban của user quản lý',
    calculation: 'Lấy phòng ban của cán bộ quản lý đã xác định theo thứ tự ưu tiên; chỉ giữ mã phòng thuộc đúng chi nhánh quản lý và có trong danh mục tổ chức.',
    reconciliation: 'Đối chiếu cặp mã chi nhánh + mã phòng với OrgDepartment; không dùng phòng của cán bộ thuộc chi nhánh khác.',
  },
  MKH: {
    profileField: 'ma_kh',
    actualSource: 'Kho CIF.CUSTNO',
    calculation: 'CIF là tập khách hàng nền cho mọi kỳ. Chuẩn hóa CUSTNO thành mã khách hàng lõi và dùng mã lõi để ghép các nguồn nghiệp vụ tại bước xử lý khách hàng.',
    reconciliation: 'Khóa duy nhất của Profile là period_key + mã KH lõi CIF; nguồn không khớp CIF vẫn được giữ trong kho đối chiếu, không tự sinh Profile từ DP01.',
  },
  TENKH: {
    profileField: 'ten_kh',
    actualSource: 'Kho CIF.NMLOC',
    calculation: 'Lấy NMLOC của bản ghi hiện hành trong Kho CIF theo mã khách hàng lõi.',
    reconciliation: 'Đối chiếu theo CUSTNO CIF; tên ở nguồn nghiệp vụ chỉ dùng để phát hiện chênh lệch, không ghi đè tên CIF.',
  },
  TEN_CHUDN: {
    profileField: 'ten_chu_doanh_nghiep',
    actualSource: 'CIF.GD_TEN',
    calculation: 'Lấy tên chủ doanh nghiệp/người đại diện từ cột GD_TEN trong bản ghi CIF hiện hành của khách hàng lõi.',
    reconciliation: 'Đối chiếu theo mã khách hàng lõi; giữ nguyên giá trị nguồn và bỏ khoảng trắng thừa.',
  },
  CCCD: {
    profileField: 'so_cccd',
    actualSource: 'CIF.REGNO; dự phòng DP01.ID_NUMBER',
    calculation: 'Ưu tiên REGNO trong Kho CIF; chỉ dùng ID_NUMBER của DP01 cùng kỳ khi CIF chưa có.',
    reconciliation: 'Đối chiếu theo mã khách hàng lõi, giữ kiểu chuỗi để không mất số 0 đầu.',
  },
  MST: {
    profileField: 'ma_so_thue',
    actualSource: 'CIF.TAXNO',
    calculation: 'Lấy nguyên TAXNO từ Kho CIF và lưu dạng chuỗi.',
    reconciliation: 'Không ép kiểu số để giữ nguyên dấu gạch ngang và số 0 đầu.',
  },
  NGAY_THANHLAP: {
    profileField: 'ngay_thanh_lap',
    actualSource: 'CIF.ISSUEDT4',
    calculation: 'Chuyển ISSUEDT4 từ YYYYMMDD thành kiểu ngày.',
    reconciliation: 'Giá trị sai định dạng hoặc ngoài miền ngày hợp lệ được để trống và theo dõi ở chất lượng CIF.',
  },
  DIACHI: {
    profileField: 'dia_chi',
    actualSource: 'CIF.ADDR1LOC + ADDR2LOC + ADDR3LOC',
    calculation: 'Bỏ phần rỗng, trim từng phần rồi ghép bằng dấu phẩy và khoảng trắng.',
    reconciliation: 'So sánh với full_address đã chuẩn hóa trong Kho CIF.',
  },
  GIOITINH: {
    profileField: 'gioi_tinh',
    actualSource: 'CIF.NAME_3',
    calculation: 'Chỉ lấy NAME_3 khi khách hàng CIF là cá nhân; khách hàng tổ chức để trống.',
    reconciliation: 'Kiểm tra đồng thời loại khách hàng và giá trị giới tính nguồn.',
  },
  NAM_SINH: {
    profileField: 'ngay_sinh',
    actualSource: 'CIF.NAME_1 / CIF.GD_NGAYSINH',
    calculation: 'Cá nhân lấy NAME_1 dạng YYYYMMDD; tổ chức lấy GD_NGAYSINH dạng DD/MM/YYYY.',
    reconciliation: 'Chuyển về kiểu ngày thống nhất và để trống nếu nguồn không hợp lệ.',
  },
  'NGHE NGHIEP': {
    profileField: 'nghe_nghiep',
    actualSource: 'CIF.PROFNM',
    calculation: 'Lấy nguyên nghề nghiệp/ngành nghề kinh doanh từ PROFNM trong Kho CIF.',
    reconciliation: 'Đối chiếu theo mã khách hàng lõi và bản ghi CIF hiện hành.',
  },
  LOAIKH: {
    profileField: 'loai_khach_hang',
    actualSource: 'Kho CIF.CUSTDTLTPCD',
    calculation: 'Lấy CUSTDTLTPCD từ bản ghi CIF hiện hành theo mã khách hàng lõi.',
    reconciliation: 'Đối chiếu với danh mục loại khách hàng CIF; DP01 không còn là nguồn master khách hàng.',
  },
  DIEN_THOAI: {
    profileField: 'telephone',
    actualSource: 'DP01',
    calculation: 'Lấy MAX(TELEPHONE) khác NULL của các bản ghi DP01 cùng MA_KH.',
    reconciliation: 'Chuẩn hóa số điện thoại, kiểm tra độ dài và các số khác nhau trên cùng MA_KH.',
  },
  MACB: {
    profileField: 'ma_cb',
    actualSource: 'User–CIF / DP01 + người dùng hệ thống; dự phòng LN01',
    calculation: 'Ưu tiên user gắn trực tiếp mã CIF. Nếu chọn chi nhánh theo tổng số dư DP01 thì chỉ lấy EMPLOYEE_NUMBER/EMPLOYEE_NAME hợp lệ tại chính chi nhánh đó; không mượn cán bộ từ chi nhánh khác. Chỉ dự phòng LN01 khi khách hàng không có DP01.',
    reconciliation: 'Đối chiếu mã nhân viên hoặc mã CBTD với user, chi nhánh và phòng ban; không khớp user trong chi nhánh quản lý thì để trống.',
  },
  TENCB: {
    profileField: 'ten_can_bo',
    actualSource: 'User–CIF / DP01 + người dùng hệ thống; dự phòng LN01',
    calculation: 'Lấy họ tên user theo cùng quy tắc xác định MACB; tên tổng quan chỉ lấy từ quan hệ thuộc chi nhánh chính, từng chi nhánh không có cán bộ khớp thì để trống.',
    reconciliation: 'Đối chiếu mã nhân viên/mã CBTD với user và cặp chi nhánh + phòng ban; không nhân một cán bộ sang các chi nhánh khác.',
  },
  DS_TKTT: {
    profileField: 'doanh_so_chuyen_tien_ve_tk',
    actualSource: 'GL02',
    calculation: 'Lọc LOCAC = 421101 và TRTP = Normal; tách mã KH lõi sau dấu gạch ngang trong CUSTOMER; DS_TKTT = SUM(CRAMOUNT) theo mã KH lõi.',
    reconciliation: 'Ghép đủ các phần GL02, loại CUSTOMER 000000000 và kiểm tra tổng Nợ = tổng Có của toàn bộ bộ file.',
  },
  NGAY_UPDATE: {
    profileField: 'last_tktt_transaction_at',
    actualSource: 'GL02',
    calculation: 'MAX(CRTDTM), dự phòng MAX(TRDATE), sau khi lọc LOCAC = 421101, TRTP = Normal và CUSTOMER hợp lệ.',
    reconciliation: 'Đối chiếu thời điểm giao dịch cuối cùng và số ngày từ giao dịch đó đến ngày cuối kỳ.',
  },
  TKTT1: {
    profileField: 'deposit-accounts.primary_accounts[0].account_number',
    actualSource: 'DP01 + PF14',
    calculation: 'Lọc tài khoản thanh toán DP01 có MONTH_TERM = 0, chưa đóng và không inactive. Ưu tiên tài khoản thuộc chi nhánh chính, sau đó số dư bình quân PF14 giảm dần, số dư cuối kỳ giảm dần và số tài khoản tăng dần; lấy hạng 1.',
    reconciliation: 'Ghép DP01.SO_TAI_KHOAN với PF14.ACCOUNTNO theo kỳ + chi nhánh + mã KH; OSB và tài khoản số đẹp vẫn thuộc TKTT.',
  },
  TKTT2: {
    profileField: 'deposit-accounts.primary_accounts[1].account_number',
    actualSource: 'DP01 + PF14',
    calculation: 'Cùng tập và thứ tự xếp hạng TKTT1; lấy tài khoản hợp lệ ở hạng 2.',
    reconciliation: 'Đối chiếu danh sách xếp hạng theo kỳ; để trống nếu khách hàng chỉ có một TKTT hợp lệ.',
  },
  TKTT3: {
    profileField: 'deposit-accounts.primary_accounts[2].account_number',
    actualSource: 'DP01 + PF14',
    calculation: 'Cùng tập và thứ tự xếp hạng TKTT1; lấy tài khoản hợp lệ ở hạng 3.',
    reconciliation: 'Đối chiếu danh sách xếp hạng theo kỳ; để trống nếu khách hàng có ít hơn ba TKTT hợp lệ.',
  },
  SODU_TGCKH: {
    profileField: 'so_du_tien_gui',
    actualSource: 'PF14 + tỷ giá DP01',
    calculation: 'SUM(MONTHLYENDBALANCE × EXCHANGE_RATE) với MONTERM > 0, theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu tổng PF14 theo MA_KH/chi nhánh/CCY và bảng tỷ giá của kỳ.',
  },
  SODU_TKTTBQ: {
    profileField: 'so_du_tgtt_binh_quan',
    actualSource: 'PF14 + tỷ giá DP01',
    calculation: 'SUM(AVERAGEBALANCE × EXCHANGE_RATE) với MONTERM = 0, theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu tổng số dư bình quân PF14 theo MA_KH/chi nhánh và từng loại tiền.',
  },
  DUNO_NHTT: {
    profileField: 'du_no_ngan_han',
    actualSource: 'PF10',
    calculation: 'SUM(EOMBAL) theo mã KH lõi và các chi nhánh với LNTYPE = 100.',
    reconciliation: 'Chỉ đưa vào Profile khi mã KH lõi có trong DP01 của kỳ; chi tiết giữ theo TRBRCD và ACCTNO.',
  },
  DUNO_NHTTBQ: {
    profileField: 'du_no_ngan_han_bq',
    actualSource: 'PF10',
    calculation: 'SUM(AVGBAL) theo mã KH lõi và các chi nhánh với LNTYPE = 100.',
    reconciliation: 'Đối chiếu tổng các LDS PF10 theo khách hàng, chi nhánh và loại vay 100.',
  },
  DUNO_TDHTT: {
    profileField: 'du_no_trung_dai_han',
    actualSource: 'PF10',
    calculation: 'SUM(EOMBAL) với LNTYPE thuộc 110 hoặc 120.',
    reconciliation: 'Gộp trung hạn và dài hạn ở chỉ tiêu tổng, vẫn giữ mã 110/120 tại chi tiết LDS.',
  },
  DUNO_TDHTTBQ: {
    profileField: 'du_no_trung_dai_han_bq',
    actualSource: 'PF10',
    calculation: 'SUM(AVGBAL) với LNTYPE thuộc 110 hoặc 120.',
    reconciliation: 'Đối chiếu tổng bình quân theo từng chi nhánh trước khi cộng toàn khách hàng.',
  },
  DUNO_TC: {
    profileField: 'du_no_thau_chi',
    actualSource: 'PF10',
    calculation: 'SUM(EOMBAL) với LNTYPE = 241.',
    reconciliation: 'Đối chiếu các LDS thấu chi PF10 theo mã KH lõi và chi nhánh.',
  },
  DUNO_TCBQ: {
    profileField: 'du_no_thau_chi_bq',
    actualSource: 'PF10',
    calculation: 'SUM(AVGBAL) với LNTYPE = 241.',
    reconciliation: 'Đối chiếu bình quân các LDS thấu chi PF10 theo mã KH lõi và chi nhánh.',
  },
  TKSODEP: {
    profileField: 'tk_so_dep',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN TKTT_TK_SODEP > 0 THEN 1 ELSE 0 END) theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu cờ sử dụng với CN05; một bản ghi dương thì khách hàng được xác định có sử dụng.',
  },
  AGRIBANKPLUS: {
    profileField: 'agribank_plus',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN DK_AGRIBANK_PLUS > 0 THEN 1 ELSE 0 END) theo MA_KH và chi nhánh.',
    reconciliation: 'Đối chiếu số lượng đăng ký trên CN05; tổng hợp toàn khách hàng bằng MAX qua các chi nhánh.',
  },
  OTT: {
    profileField: 'tin_nhan_ott',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN DK_AGRIBANK_PLUS_OTT > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu cờ OTT theo MA_KH/chi nhánh trong CN05.',
  },
  EBANKING: {
    profileField: 'e_banking',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN SMS_BANKING > 0 THEN 1 ELSE 0 END); tên trường đích hiện là e_banking.',
    reconciliation: 'Đối chiếu với SMS_BANKING của CN05; cần nghiệp vụ xác nhận phạm vi có đúng toàn bộ E-Banking hay không.',
  },
  SMS_TKTV: {
    profileField: 'sms_nhac_no_vay',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN VV_SMS_TIEN_VAY > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu cờ dịch vụ vay trên CN05 theo MA_KH/chi nhánh.',
  },
  SMS_TKTG: {
    profileField: 'sms_tien_gui',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN TG_SMS_TIEN_GUI > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu cờ dịch vụ tiền gửi trên CN05 theo MA_KH/chi nhánh.',
  },
  THE_GNND: {
    profileField: 'the_ghi_no_noi_dia',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN THE_GHI_NO_NOI_DIA > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu số lượng thẻ ghi nợ nội địa trong CN05.',
  },
  THE_GNQT: {
    profileField: 'the_ghi_no_quoc_te',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN THE_GHI_NO_QUOC_TE > 0 THEN 1 ELSE 0 END) theo mã khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu cờ thẻ ghi nợ quốc tế trên CN05 theo MA_KH/chi nhánh; hồ sơ tổng lấy MAX qua các chi nhánh.',
  },
  THE_LOCVIET: {
    profileField: 'the_td_loc_viet',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN THE_TIN_DUNG_NOI_DIA > 0 THEN 1 ELSE 0 END); hiện ánh xạ vào cờ thẻ Lộc Việt.',
    reconciliation: 'Đối chiếu THE_TIN_DUNG_NOI_DIA; cần xác nhận nghiệp vụ có đồng nhất với toàn bộ thẻ Lộc Việt.',
  },
  THE_TDQT: {
    profileField: 'the_td_quoc_te',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN THE_TIN_DUNG_QUOC_TE > 0 THEN 1 ELSE 0 END).',
    reconciliation: 'Đối chiếu số lượng thẻ tín dụng quốc tế trong CN05.',
  },
  SODU_TKTT: {
    profileField: 'pf14_account_balances.monthlyendbalance',
    actualSource: 'PF14',
    calculation: 'SUM(MONTHLYENDBALANCE × tỷ giá) theo mã KH lõi với MONTERM = 0; chi tiết được khai thác tại tab Tiền gửi.',
    reconciliation: 'Đối chiếu từng ACCOUNTNO, TRBRCD, CUSTSEQ và CCY của PF14; tổng chi tiết phải bằng số dư TKTT của khách hàng.',
  },
  SODU_TGCKHBQ: {
    profileField: 'pf14_account_balances.averagebalance',
    actualSource: 'PF14',
    calculation: 'SUM(AVERAGEBALANCE × tỷ giá) theo mã KH lõi với MONTERM > 0.',
    reconciliation: 'Đối chiếu số dư bình quân từng tài khoản PF14 có kỳ hạn trước khi cộng theo khách hàng và chi nhánh.',
  },
  PHAN_LOAIKH: {
    profileField: 'bc06_customer_classifications.segment_branch',
    actualSource: 'BC06',
    calculation: 'Lấy SEGMENT_BRANCH theo mã khách hàng và chi nhánh tại kỳ; lịch sử phân khúc được giữ theo từng kỳ BC06.',
    reconciliation: 'Đối chiếu CUSTOMER_CODE, BRANCH_CODE và CLASSIFICATION_MONTH của BC06; không ghi đè phân khúc giữa các chi nhánh.',
  },
  DUNO_XAU: {
    profileField: 'bc29_customer_credit_risks.total_outstanding',
    actualSource: 'BC29',
    calculation: 'SUM(TOTAL_OUTSTANDING) theo khách hàng với DEBT_GROUP thuộc 3, 4 hoặc 5.',
    reconciliation: 'Đối chiếu tổng dư nợ BC29 theo CUSTOMER_CODE/BRANCH_CODE và nhóm nợ; kỳ không có nhóm 3-5 được ghi nhận là không phát sinh.',
  },
  DUNO_XLRR: {
    profileField: 'du_no_xlrr',
    actualSource: 'RR01',
    calculation: 'SUM(DUNO_GOC_HIENTAI) trực tiếp theo mã KH lõi.',
    reconciliation: 'Đối chiếu chi tiết theo LAV/LDS và kiểm tra DUNO_GOC_BAN_DAU - DOC_DAUKY_DA_THU_HT = DUNO_GOC_HIENTAI.',
  },
  DS_THUNO_XLRR: {
    profileField: 'ds_thu_no_xlrr',
    actualSource: 'RR01',
    calculation: 'SUM(THU_GOC) + SUM(THU_LAI) trực tiếp theo mã KH lõi.',
    reconciliation: 'Đối chiếu tổng ngoài hồ sơ với chi tiết từng LAV/LDS trong RR01.',
  },
  DPRR_CHUNG_TT: {
    profileField: 'dprr_chung_tt',
    actualSource: 'LN01',
    calculation: '(SUM(DU_NO nhóm 1-4 kỳ này) - SUM(DU_NO nhóm 1-4 kỳ trước)) × 0,75%, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu CUSTSEQ, BRCODE và NHOM_NO giữa hai kỳ LN01; giá trị âm được giữ để phản ánh hoàn nhập.',
  },
  DPRR_CHUNG_LK: {
    profileField: 'dprr_chung_lk',
    actualSource: 'LN01',
    calculation: 'SUM(DU_NO nhóm 1-4 cuối kỳ) × 0,75%, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu CUSTSEQ, BRCODE, NHOM_NO và tổng DU_NO của LN01 tại kỳ.',
  },
  DPRR_CUTHE_TT: {
    profileField: 'dprr_cuthe_tt',
    actualSource: 'BC29',
    calculation: 'SUM(SO_TRICH_LAP_TRONG_KY nhóm 2-5 kỳ này) trừ cùng chỉ tiêu kỳ trước, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu MA_KH, BRANCH_CODE và NHOM_NO giữa hai kỳ BC29; giá trị âm là hoàn nhập.',
  },
  DPRR_CUTHE_LK: {
    profileField: 'dprr_cuthe_lk',
    actualSource: 'BC29',
    calculation: 'SUM(SO_TRICH_LAP_TRONG_KY) của nhóm nợ 2-5 tại kỳ, theo khách hàng lõi và chi nhánh.',
    reconciliation: 'Đối chiếu MA_KH, BRANCH_CODE, NHOM_NO và SO_TRICH_LAP_TRONG_KY trong BC29.',
  },
  PHI_BAOLANH: {
    profileField: 'phi_bao_lanh',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 7040: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản 7040xx và tổng phát sinh Có/Nợ trong KH02.',
  },
  PHI_CHUYENTIEN: {
    profileField: 'phi_chuyen_tien',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 711001 hoặc 711002: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản phí chuyển tiền và tổng phát sinh Có/Nợ trong KH02.',
  },
  PHI_NHDT: {
    profileField: 'phi_nhdt',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 711036, 711037 hoặc 711039: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản phí NHĐT và tổng phát sinh Có/Nợ trong KH02.',
  },
  ABIC_BATD: {
    profileField: 'abic_batd',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 714: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tài khoản 714xxx và tổng phát sinh Có/Nợ trong KH02.',
  },
  PHI_KDNT: {
    profileField: 'phi_kdnt',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 721001: SUM(CRAMT) - SUM(DRAMT), gom theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Chuẩn hóa CUSTSEQ thành mã KH lõi; chỉ đưa vào C360 khi mã tồn tại trong Kho CIF.',
  },
  PHI_LC: {
    profileField: 'phi_lc',
    actualSource: 'KH02',
    calculation: 'Với ACCTCD bắt đầu 709002: SUM(CRAMT) - SUM(DRAMT), gom theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu mã KH lõi với Kho CIF tại bước xử lý KH và giữ mã không khớp trong bảng đối chiếu.',
  },
  PHI_TTQT: {
    profileField: 'phi_ttqt',
    actualSource: 'KH02',
    calculation: 'ACCTCD từ 711003 đến 711014 hoặc bắt đầu 711096: SUM(CRAMT) - SUM(DRAMT), theo KH lõi và chi nhánh.',
    reconciliation: 'Mã 711002 chỉ thuộc PHI_CHUYENTIEN; mỗi giao dịch được cộng vào đúng một nhóm phí chính.',
  },
  PHI_THE: {
    profileField: 'phi_the',
    actualSource: 'KH02',
    calculation: 'ACCTCD bắt đầu 711015, 711016, 711022-711028, 711051, 711052 hoặc 711059: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Đối chiếu tổng phát sinh Có/Nợ từng đầu tài khoản với KH02; giữ nguyên khoản âm do hoàn/điều chỉnh phí.',
  },
  PHI_KHAC: {
    profileField: 'phi_khac',
    actualSource: 'KH02',
    calculation: 'ACCTCD bắt đầu 711031, 711035, 711042, 711044 hoặc 711098: SUM(CRAMT) - SUM(DRAMT), theo CUSTSEQ và chi nhánh.',
    reconciliation: 'Không lấy 711037, 711039 và 711096 vì các mã này đã thuộc PHI_NHDT/PHI_TTQT; một mã chỉ thuộc một nhóm phí chính.',
  },
  TTQT: {
    profileField: 'ttqt',
    actualSource: 'KH02',
    calculation: 'Gắn cờ 1 nếu PHI_KDNT khác 0 hoặc PHI_LC khác 0 hoặc PHI_TTQT khác 0 trong kỳ.',
    reconciliation: 'Suy ra sau khi tổng hợp ba loại phí và đối chiếu mã KH với Kho CIF.',
  },
  THUHO_DIEN: {
    profileField: 'thuho_dien',
    actualSource: 'Bill Payment + DP01',
    calculation: 'Lọc Mã DV theo danh sách cấu hình thu hộ điện; lấy STK chuyển rồi ghép DP01.SO_TAI_KHOAN để xác định mã KH lõi. Có ít nhất một giao dịch hợp lệ thì gắn cờ 1.',
    reconciliation: 'Đối chiếu Mã DV với business_matching_rules, STK chuyển với DP01 và kiểm tra giao dịch thuộc đúng kỳ xử lý.',
  },
  THUHO_NUOC: {
    profileField: 'thuho_nuoc',
    actualSource: 'Bill Payment + DP01',
    calculation: 'Lọc Mã DV theo danh sách cấu hình thu hộ nước; ghép STK chuyển với DP01.SO_TAI_KHOAN để lấy mã KH lõi và gắn cờ sử dụng.',
    reconciliation: 'Đối chiếu mã dịch vụ đang hiệu lực trong business_matching_rules và các tài khoản Bill Payment không tìm thấy trong DP01.',
  },
  THUHO_DT: {
    profileField: 'thuho_dt',
    actualSource: 'Bill Payment + DP01/CN05/CIF',
    calculation: 'Lọc Mã DV 312, 333, 360, 409, 363. STK thường ghép DP01; STK 8888 ghép phần mã lõi với CN05; user deposit tách CCCD 9-12 số trong Nội dung rồi ghép CIF.',
    reconciliation: 'Chỉ gắn cờ khi xác định được KH. Giao dịch không tìm được tài khoản/mã KH/CCCD không được suy diễn vào C360.',
  },
  HKD_TK: {
    profileField: 'hkd_tk',
    actualSource: 'DP01',
    calculation: 'Theo mã KH lõi, nếu có tài khoản DP01 với CUST_TYPE = 570 thì gắn cờ 1; đồng thời lưu danh sách SO_TAI_KHOAN hộ kinh doanh.',
    reconciliation: 'Đối chiếu MA_KH, CUST_TYPE và từng SO_TAI_KHOAN trong DP01; loại trùng số tài khoản trước khi lưu.',
  },
  ABIC_BATK: {
    profileField: 'abic_batk',
    actualSource: 'Bill Payment + DP01',
    calculation: 'Lọc Mã DV = 1218 và Số tiền = 77.000 theo cấu hình; ghép STK chuyển với DP01.SO_TAI_KHOAN để xác định khách hàng.',
    reconciliation: 'Đối chiếu đồng thời mã dịch vụ, số tiền cấu hình, tài khoản chuyển và kỳ giao dịch; một giao dịch hợp lệ thì gắn cờ 1.',
  },
  ABIC_BATHE: {
    profileField: 'abic_bathe',
    actualSource: 'Bill Payment + DP01',
    calculation: 'Lọc Mã DV = 1218 và Số tiền = 18.000 theo cấu hình; ghép STK chuyển với DP01.SO_TAI_KHOAN để xác định khách hàng.',
    reconciliation: 'Đối chiếu đồng thời mã dịch vụ, số tiền cấu hình, tài khoản chuyển và kỳ giao dịch; một giao dịch hợp lệ thì gắn cờ 1.',
  },
  LOATHANTAI: {
    profileField: 'loa_bien_dong_so_du',
    actualSource: 'CN05',
    calculation: 'MAX(CASE WHEN LOA_BIEN_DONG_SO_DU > 0 THEN 1 ELSE 0 END) theo mã khách hàng và chi nhánh.',
    reconciliation: 'Đối chiếu cờ sử dụng loa biến động số dư trong CN05; không suy diễn từ Agribank Plus hoặc SMS.',
  },
  POS: {
    profileField: 'pos',
    actualSource: 'Báo cáo POS toàn tỉnh + DP01 + Kho CIF',
    calculation: 'Chuẩn hóa POS.SỐ_TÀI_KHOẢN rồi ghép DP01.SO_TAI_KHOAN cùng kỳ để lấy DP01.MA_KH; mã KH lõi tiếp tục tham chiếu Kho CIF tại bước xử lý KH. Có ít nhất một Merchant POS hiện hữu thì gắn POS = 1, kể cả kỳ không phát sinh giao dịch.',
    reconciliation: 'Không dùng Merchant ID, mã thiết bị hoặc tên cửa hàng làm mã KH. Kỳ 06 lấy sheet T6, kỳ 07 lấy T7; kỳ 08 kế thừa ảnh chụp T7 cho tới khi có nguồn T8.',
  },
  SO_THIET_BI_POS: {
    profileField: 'so_thiet_bi_pos',
    actualSource: 'Báo cáo POS toàn tỉnh',
    calculation: 'Theo từng quan hệ POS, lấy giá trị lớn hơn giữa Số lượng thiết bị khai báo và số mã thiết bị khác nhau; sau đó cộng theo mã KH lõi và chi nhánh.',
    reconciliation: 'Gộp các dòng thiết bị thuộc cùng tài khoản/Merchant trước khi cộng để không nhân lặp số lượng.',
  },
  POS_MOI: {
    profileField: 'pos_moi',
    actualSource: 'Báo cáo POS toàn tỉnh qua các sheet tháng',
    calculation: 'Quan hệ tài khoản/Merchant có ở ảnh chụp kỳ này nhưng không có ở sheet liền trước thì POS_MOI = 1.',
    reconciliation: 'Không suy diễn POS mới cho kỳ 08 khi nguồn mới nhất mới dừng ở sheet T7.',
  },
  POS_KHONG_HOAT_DONG: {
    profileField: 'pos_khong_hoat_dong',
    actualSource: 'Báo cáo POS toàn tỉnh',
    calculation: 'Quan hệ POS vẫn tồn tại nhưng Số món giao dịch trong tháng bằng 0 thì POS_KHONG_HOAT_DONG = 1.',
    reconciliation: 'Khách hàng vẫn được tích xanh POS; trạng thái không hoạt động chỉ phản ánh không phát sinh giao dịch trong kỳ.',
  },
};

export function mappingRuleFor(field) {
  return implemented[field.code] || {
    profileField: null,
    actualSource: field.source,
    calculation: `Chưa có cột đích hoặc công thức xử lý trong customer_period_profiles. Nguồn dự kiến: ${field.source}.`,
    reconciliation: 'Chưa triển khai đối chiếu tự động; cần chốt nguồn, khóa nối và quy tắc nghiệp vụ trước khi đưa vào Profile.',
  };
}
